import type { Metadata } from "next";
import "../globals.css";
import { Sidebar } from "../../components/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex md:flex-row flex-col md:h-screen">
            <Sidebar />
            <div className="overflow-y-auto w-full">{children}</div>
        </div>
    );
}
